[tool.poetry]
name = "openrtist"
version = "0.1.0"
description = "Openrtist Python Server"
authors = ["Carnegie Mellon University <satya+group@cs.cmu.edu>"]
license = "Apache-2.0"
readme = "README.md"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Environment :: X11 Applications",
    "Intended Audience :: End Users/Desktop",
]
packages = [{include = "openrtist", from = "."}]

[tool.poetry.dependencies]
python = "^3.7"
websockets = "8.*"
gabriel_protocol = "*"
opencv-python = ">=3, <5"
protobuf = "3.18.*"
pillow = "<7"
torchvision = ">=0.3, <0.5"
py-cpuinfo = "*"
azure-cognitiveservices-vision-face = "*"
asyncio = "*"

[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
isort = "^5.11.0"

[tool.black]
#skip-string-normalization = true
include = '\.pyi?$'
exclude = '''
(
  /(
     \.git
   | \.venv
  )/
  # don't rewrite generated files
  | src/openrtist/openrtist_pb2.py
)
'''

[tool.isort]
profile = "black"

[tool.mypy]
check_untyped_defs = true
files = ["src"]

[tool.poetry.scripts]
openrtist = "scripts.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
